<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<br>
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('home') ?>">Home</a></li>
    </ol>
</nav>

<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-4">Bienvenido al Portal de Trabajos Fin de Estudios de la UOC.</h1>

    <p>
        Enhorabuena si has llegado hasta aquí. A través de esta aplicación podrás ver tu
        perfil de estudiante y proponer o solicitar adherirte a un Trabajo ofertado por un
        profesor. Cuando hayas terminado tu proyecto final, podrás subirlo en esta plataforma.
    </p>

    <hr class="my-4">

    <!-- <a class="btn btn-primary btn-lg" href="<? //= $this->Url('principal') ?>">
        Mi perfil &raquo;
    </a>

    <a class="btn btn-primary btn-lg" href="<? //= $this->Url('propuesta-oferta') ?>">
        Estudios de Grado &raquo;
    </a>

    <a class="btn btn-primary btn-lg" href="<? //= $this->Url('propuesta-oferta') ?>">
        Estudios de Máster&raquo;
    </a>

    <a class="btn btn-primary btn-lg" href="<? //= $this->Url('solicitud-deposito') ?>">
        Biblioteca UOC &raquo;
    </a> -->
</div>

<div class="row">
    <div class="col-md-4">
        <div class="card">
            <h2 class="card-header">Trabajos Ofertados</h2>
            <div class="card-body">
                <p>
                    Puedes investigar sobre los distintos trabajos ofertados por los docentes
                    de tú plan de estudios. Descubre que temas son los que más te interesan
                    y la variedad de proyectos disponibles en los que puedes embarcarte.
                </p>

                <a class="btn btn-primary" href="<?= $this->Url('trabajos-ofertados') ?>">Trabajos Ofertados &raquo;</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <h2 class="card-header">Proponer Oferta</h2>
            <div class="card-body">
                <p>
                    Si quieres proponer un tema para realizar tu Trabajo Final, expón tus ideas y
                    detalla una descripción de lo que quieres hacer. Tu propuesta será revisada
                    y si es aduada para la asignatura, podrás realizarla.
                </p>

                <a class="btn btn-primary"
                   href="<?= $this->Url('trabajos-ofertados') ?>">
                    Proponer Oferta&raquo;
                </a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <h2 class="card-header">Solicitud de Depósito</h2>
            <div class="card-body">
                <p>
                    Si has finalizado las entragas parciales de tu asignatura final, puedes
                    adjuntar en el siguiente formulario tu Trabajo para que este pase a
                    ser evaluado.
                </p>

                <a class="btn btn-primary" href="<?= $this->Url('trabajos-ofertados') ?>">Solicitud Depósito&raquo;</a>
            </div>
        </div>
    </div>
</div>
