<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<br>
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('home') ?>">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Mi expediente</li>
    </ol>
</nav>


<div class="container-lg">
    <div class="bck-primary-ligth">
        <div class="d-flex justify-content-center">
            <p>
            <h1><b>Mi perfil UOC</b></h1></p>
        </div>
    </div>
    <br>
    <!-- for a media object-->
    <!--<img src="<? /*= $this->basePath()*/ ?>/img/user.png" class="img-thumbnail img-fluid"
         alt="imagen de perfil de un usuario">-->

    <h2>Datos del estudiante</h2>
    <div class="mb-3">
        <label for="name" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="name"
               value="<?= $this->estudiante[0]['NOMBRE'] . ' ' . $this->estudiante[0]['APELLIDO1'] . ' ' . $this->estudiante[0]['APELLIDO2'] ?>"
               readonly disabled>
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Email address</label>
        <input type="email" class="form-control" id="exampleFormControlInput1"
               placeholder="name@example.com"
               value="<?= $this->estudiante[0]['USUARIO'] . '@uoc.edu'; ?>" readonly disabled>
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Teléfono</label>
        <input type="email" class="form-control" id="exampleFormControlInput1"
               placeholder="Teléfono1"
               value="<?= $this->estudiante[0]['TELEFONO1'] ?>" readonly disabled>
    </div>

    <h2>Datos académicos</h2>
    <div class="mb-3">
        <div class="accordion" id="accordionExample">
            <?php foreach ($this->estudiante as $i => $estudios) { ?>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading<?= $i ?>">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapse<?= $i ?>" aria-expanded="true"
                                aria-controls="collapse<?= $i ?>">
                            <?= $estudios['NOMBRE_PLAN'] ?>
                        </button>
                    </h2>
                    <div id="collapse<?= $i ?>" class="accordion-collapse collapse show"
                         aria-labelledby="heading<?= $i ?>" data-bs-parent="#accordionExample">
                        <div class="accordion-body">

                            <div class="progress">
                                <div class="progress-bar" role="progressbar"
                                     style="width: <?= random_int(0, 100) ?>%;"
                                     aria-valuenow="<?= random_int(0, 100) ?>" aria-valuemin="0"
                                     aria-valuemax="100"><?= random_int(0, 100) ?>
                                </div>
                            </div>
                            <?php if (!empty($estudios['ASIGNATURAS'])) { ?>
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">Curso</th>
                                        <th scope="col">Asignatura</th>
                                        <th scope="col">Nota</th>
                                        <th scope="col">Calificación</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($estudios['ASIGNATURAS'] as $asignatura) { ?>
                                        <tr>
                                            <th scope="row"> <?= $asignatura['CURSO_ACADEMICO'] ?></th>
                                            <th> <?= $asignatura['NOMBRE_ASIGNATURA'] ?></th>
                                            <th> <?= $asignatura['NOTA_NUMERICA'] ?></th>
                                            <th> <?= $asignatura['NOTA_ALFANUMERICA'] ?></th>
                                        </tr>
                                    <?php } ?>
                                    </tbody>
                                </table>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            <?php } ?>

        </div>

        <!--<div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Propuesta de TFM</label>
            <textarea name="propuesta" class="form-control" id="exampleFormControlTextarea1"
                      rows="3"></textarea>
        </div>-->
        <!-- <div class="mb-3 form-check">
             <input type="checkbox" class="form-check-input check-normativa" id="normativa">
             <label class="form-check-label" for="normativa">He leído la normativa de TFM.</label>
         </div>-->

        <!--<button type="submit" class="btn btn-primary">Enviar</button>-->

        <!--    </div>
        </div>-->
    </div>


