<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<br>
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('home') ?>">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Solicitud de depósito</li>
    </ol>
</nav>


<div class="container-lg">

    <div class="bck-primary-ligth">
        <div class="d-flex justify-content-center">
            <p>
            <h1><b>Solicitud de depósito</b></h1></p>
        </div>
    </div>
    <br>

    <form action="solicitud-deposito" method="post" enctype="multipart/form-data">

        <br>
        <h2>Solicitud de Depósito</h2>
        <div class="alert alert-info" role="alert">
            <p>Puede realizar la solicitud de depósito indicando la asignatura asociada y el plan de estudios.</p>
        </div>


        <div class="mb-3">
            <label for="name" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="name"
                   value="<?= $this->estudiante[0]['NOMBRE'] . ' ' . $this->estudiante[0]['APELLIDO1'] . ' ' . $this->estudiante[0]['APELLIDO2'] ?>"
                   readonly disabled>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Email address</label>
            <input type="email" class="form-control" id="exampleFormControlInput1"
                   placeholder="name@example.com"
                   value="<?= $this->estudiante[0]['USUARIO'] . '@uoc.edu'; ?>" readonly disabled>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Teléfono</label>
            <input type="email" class="form-control" id="exampleFormControlInput1"
                   placeholder="Teléfono1"
                   value="<?= $this->estudiante[0]['TELEFONO1'] ?>" readonly disabled>
        </div>

        <!--<div class="mb-3">
            <label for="estudios" class="form-label">Estudios asociados al trabajo</label>
            <select for="estudios" class="form-control" aria-label="Default select example" name="estudios">
                <option selected>Seleccione</option>
                <?php //foreach ($this->estudiante as $estudio) { ?>
                    <option value="<? //= $estudio['COD_PLAN'] ?>#<? //= $estudio['COD_AREA'] ?>>"><? //= $estudio['NOMBRE_PLAN'] ?></option>
                <?php //} ?>
            </select>
        </div>-->


        <div class="mb-3">
            <label class="form-label">Trabajo para depositar</label>
            <select for="trabajo" class="form-control" aria-label="Default select example" name="cod_oferta">
                <option selected>Seleccione el trabajo a depositar</option>
                <?php foreach ($this->misOfertas as $oferta) { ?>
                    <option value="<?= $oferta['COD_OFERTA']; ?>"><?= $oferta['NOMBRE_PLAN'] . ' - ' . $oferta['TITULO'] ?></option>
                <?php } ?>
            </select>
        </div>

        <div class="mb-3">
            <label for="descripción" class="form-label">Descripción del Trabajo</label>
            <textarea name="descripcion" placeholder="Descripción" class="form-control" id="descripcion"
                      rows="3" disabled
                      readonly> </textarea>
        </div>

        <div class="mb-3">
            <label for="docente" class="form-label">Docente</label>
            <input type="docente" class="form-control" id="docente"
                   value="" readonly disabled>
        </div>


        <label for="idioma" class="form-label">Idioma del trabajo </label>
        <div class="mb-3">
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="idioma" id="flexRadioDefault1" value="cas" checked>
                <label class="form-check-label" for="flexRadioDefault1">
                    Catalán
                </label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="idioma" id="flexRadioDefault2" value="cat">
                <label class="form-check-label" for="flexRadioDefault2">
                    Castellano
                </label>
            </div>
        </div>
        <div class="mb-3">
            <label for="formFile" class="form-label">Archivo</label>
            <input class="form-control" name="archivo" type="file" id="formFile">
        </div>

        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input check-normativa" name="normativa" id="normativa">
            <label class="form-check-label" for="normativa">He leído la normativa de TFE y acepto.</label>
        </div>


        <button type="submit" class="btn btn-primary">Solicitar depósito</button>
    </form>


    <?php if (!empty($propuestas)) { ?>
        <hr>
        <h2>Mis propuestas de Trabajos Fin de Estudios</h2>
        <br>
        <div class="alert alert-info" role="alert">
            <p>Sólo podrá solicitar a través de la aplicación la anulación de la oferta en caso de que aún no esté
                aceptada por
                ningún docente. En caso contrario, tendrá que contactar con el docente por correo motivando la
                solicitud.</p>
        </div>
        <table class="table table-striped" id="table_extensible">
            <thead>
            <tr>
                <th scope="col">Curso</th>
                <th class="col-md-3" scope="col">Título</th>
                <th scope="col">Plan</th>
                <th scope="col">Docente</th>
                <th scope="col">Estado</th>
                <th scope="col">Acciones</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($propuestas as $trabajo) { ?>
                <tr>
                    <th scope="row"> <?= $trabajo['CURSO_ACADEMICO'] ?></th>
                    <th class="col-md-3"> <?= strtoupper($trabajo['TITULO']); ?></th>
                    <th class="col-md-3"> <?= $trabajo['NOMBRE_PLAN'] ?></th>
                    <th><?php
                        if (!empty($trabajo['NOMBRE_DOCENTE'])) {
                            ?>
                            <?= '<a href="mailto:' . $trabajo['USUARIO_DOCENTE'] . '@uoc.edu"><i class="fa-solid fa-envelope"></i></a> ' . $trabajo['NOMBRE_DOCENTE'] ?>
                        <?php } ?>
                    </th>
                    <th>  <?php
                        if ($trabajo['ESTADO_OFERTA'] == 'Anulada')
                            echo '<span class="badge bg-danger text-white">Anulada</span>';
                        else if ($trabajo['ESTADO_OFERTA'] == 'Validada')
                            echo '<span class="badge bg-success text-white">Validada</span>';
                        else if ($trabajo['ESTADO_OFERTA'] == 'Pendiente')
                            echo '<span class="badge bg-primary text-white">Pendiente</span>'; ?>
                    </th>
                    <th class="col-md-1">
                        <div class="d-grid gap-1">
                            <?php if (($trabajo['ESTADO_OFERTA'] <> 'Anulada')) { ?>
                                <button type="button" class="btn btn-sm btn-accion btn-danger"
                                        data-accion="anular"
                                        data-flg="1"
                                        data-plan_trabajo="<?= $trabajo['COD_PLAN'] ?>"
                                        data-cod="<?= $trabajo['COD_OFERTA']; ?>">
                                    Anular
                                </button>
                            <?php } ?>
                        </div>
                    </th>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    <?php } ?>
</div>



