<form action="solicitud-deposito" name="solicitudDepositoForm" method="post" enctype="multipart/form-data">
    <input type="hidden" name="flg_editar" value="1">
    <input type="hidden" name="cod_deposito_editar" id="cod_deposito_editar" value="">
    <input type="hidden" name="cod_oferta_editar" id="cod_oferta_editar" value="">

    <br>
    <h2>Solicitud de Depósito</h2>
    <div class="alert alert-warning" role="alert">
        <p>Atención, debe editar el depósito porque se le han requerido cambios en el trabajo. Suba de nuevo el
            fichero.
        </p>
    </div>

    <!--feedback form-validation-->
    <div class='alert alert-danger alert-dismissable fade show error-form' role='alert' hidden>
        <b>Revise el formulario, existen campos obligatorios que no ha completado.</b>
    </div>
    <div class='alert alert-success alert-dismissable fade show success-form' role='alert' hidden>
        <b>Formulario completado correctamente.</b>
    </div>
    <!--- -->


    <div class="mb-3">
        <label for="name" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="name"
               value="<?= $this->estudiante[0]['NOMBRE'] . ' ' . $this->estudiante[0]['APELLIDO1'] . ' ' . $this->estudiante[0]['APELLIDO2'] ?>"
               readonly disabled>
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Email address</label>
        <input type="email" class="form-control" id="exampleFormControlInput1"
               placeholder="name@example.com"
               value="<?= $this->estudiante[0]['USUARIO'] . '@uoc.edu'; ?>" readonly disabled>
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Trabajo depositado</label>
        <input type="email" class="form-control" id="trabajo_depositado"
               placeholder="trabajo depositado"
               value="" readonly disabled>
    </div>


    <div class="mb-3">
        <label class="form-label">Trabajo para depositar</label>
        <input type="email" class="form-control" id="exampleFormControlInput1"
               placeholder="Teléfono1"
               value="<?= $this->estudiante[0]['TELEFONO1'] ?>" readonly disabled>
    </div>

    <div class="mb-3">
        <label for="descripción" class="form-label">Descripción del Trabajo</label>
        <textarea name="descripcion" placeholder="Descripción" class="form-control" id="descripcion_editar_deposito"
                  rows="3" disabled
                  readonly> </textarea>
    </div>

    <div class="mb-3">
        <label for="docente" class="form-label">Docente</label>
        <input type="docente" class="form-control" id="docente_editar_deposito"
               value="" readonly disabled>
    </div>


    <label for="idioma" class="form-label">Idioma del trabajo </label>
    <div class="mb-3">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="idioma" id="flexRadioDefault1_editar_deposito"
                   value="cas" disabled checked
                   readonly>
            <label class="form-check-label" for="flexRadioDefault1">
                Catalán
            </label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="idioma" id="flexRadioDefault2_editar_deposito"
                   value="cat" disabled
                   readonly>
            <label class="form-check-label" for="flexRadioDefault2">
                Castellano
            </label>
        </div>
    </div>
    <div class="mb-3">
        <label for="formFile" class="form-label">Archivo</label>
        <input class="form-control" name="archivo_editar" type="file" id="formFile_editar_deposito">
    </div>

    <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input check-normativa" name="normativa" id="normativa">
        <label class="form-check-label" for="normativa">He leído la normativa de TFE y acepto.</label>
    </div>

    <!--trigger para submit modal --->
    <button type="button" class="btn btn-primary boton_modal" data-bs-toggle="modal" hidden
            data-bs-target="#confirmarDepositoModal">Solicitar deposito modal
    </button>

    <!--trigger para el form-validation -->
    <button type="submit" class="btn btn-primary">Solicitar depósito</button>
</form>