<p>
    <button class="btn btn-dark leyenda" type="button">
        Ver leyenda de estados
    </button>
</p>
<div class="mycollapse" hidden>
    <div class="row">
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        <span class="badge bg-primary text-white" data-bs-toggle="tooltip"
                              data-bs-placement="right"
                              title="Oferta pendiente.">Pendiente</span></h5>
                    <p class="card-text">Oferta pendiente de autorización por un docente.</p>
                </div>
            </div>
        </div>
      
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        <span class="badge bg-success text-white" data-bs-toggle="tooltip"
                              data-bs-placement="right"
                              title="Oferta validada.">Validada</span></h5>
                    <p class="card-text">Oferta validada por un docente que la tutorizará.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        <span class="badge bg-danger text-white" data-bs-toggle="tooltip" data-bs-placement="right"
                              title="Oferta anulada.">Anulada</span></h5>
                    <p class="card-text">Oferta anulada por el usuario que la propone.</p>
                </div>
            </div>
        </div>

    </div>
</div>