<p>
    <button class="btn btn-dark leyenda" type="button">
        Ver leyenda de estados
    </button>
</p>
<div class="mycollapse" hidden>
    <div class="row">
        <div class="col-sm-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        <span class="badge bg-primary text-white" data-bs-toggle="tooltip"
                              data-bs-placement="top"
                              title="Trabajo autorizado.">Pendiente</span></h5>
                    <p class="card-text">Solicitud autorizada y con nota final.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
               <span class="badge bg-warning text-black" data-bs-toggle="tooltip" data-bs-placement="top"
                     title="Cambios solicitados">Cambios solicitados</span></h5>
                    <p class="card-text">Puede añadir observaciones. El estudiante podrá verlas.</p>
                </div>
            </div>
        </div>

        <div class="col-sm-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        <span class="badge bg-success text-white" data-bs-toggle="tooltip"
                              data-bs-placement="top"
                              title="Trabajo autorizado.">Autorizado</span></h5>
                    <p class="card-text">Solicitud autorizada y con nota final.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        <span class="badge bg-danger text-white" data-bs-toggle="tooltip" data-bs-placement="top"
                              title="Depósito denegado.">Denegado</span></h5>
                    <p class="card-text">Solicitud denegada.</p>
                </div>
            </div>
        </div>

    </div>
</div>