<?php

use Laminas\Session\Container;
use Tfe\Util\Constantes;

$sesion = new Container (Constantes::NOMBRE_SESION);

?>

<div class="collapse navbar-collapse justify-content-lg-evenly" id="navbarSupportedContent">
    <ul class="navbar-nav">

        <li class="nav-item">
            <a class="nav-link
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_HOME_ESTUDIANTE) echo 'active'; ?>"
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_HOME_ESTUDIANTE) echo 'aria-current="page"'; ?>
               href="<?= $this->url('home') ?>">Inicio
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_EXPEDIENTE_ESTUDIANTE) echo 'active'; ?>"
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_EXPEDIENTE_ESTUDIANTE) echo 'aria-current="page"'; ?>
               href="<?= $this->url('mi-expediente') ?>">Mi expediente
            </a>
        </li>


        <li class="nav-item">
            <a class="nav-link
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_TRABAJOS_OFERTADOS) echo 'active'; ?>"
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_TRABAJOS_OFERTADOS) echo 'aria-current="page"'; ?>
               href="<?= $this->url('trabajos-ofertados') ?>">Trabajos ofertados
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_PROPONER_OFERTA_ESTUDIANTE) echo 'active'; ?>"
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_PROPONER_OFERTA_ESTUDIANTE) echo 'aria-current="page"'; ?>
               href="<?= $this->url('propuesta-oferta') ?>">Proponer oferta
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_DEPOSITAR_ESTUDIANTE) echo 'active'; ?>"
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_DEPOSITAR_ESTUDIANTE) echo 'aria-current="page"'; ?>
               href="<?= $this->url('solicitud-deposito') ?>">Solicitud depósito
            </a>
        </li>

    </ul>

    <span class="navbar-text">
        <?php if ($sesion->offsetExists(Constantes::SESION_NOMBRE_USUARIO)) { ?>
            <i><?= $sesion->offsetGet(Constantes::SESION_NOMBRE_USUARIO) . ' ' ?></i>
        <?php } ?>
    </span>
    <span class="navbar-text">
        <a class="nav-link" href="<?= $this->url('desconectar') ?>">
            Desconectar <i class="bi bi-box-arrow-in-right"></i>
        </a>
    </span>
</div>
