<?php

use Laminas\Session\Container;
use Tfe\Util\Constantes;

$sesion = new Container (Constantes::NOMBRE_SESION);

?>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav nav-pills nav-fill nav-justified flex-grow-1 pe-4">
        <li class="nav-item">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img class="img-logo" src="<?= $this->basePath('img/logo-uoc-default.png') ?>"
                     alt="UOC-logo">
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link  <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_ALTA_OFERTA_DOCENTE) echo 'active'; ?>"
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == 'home') echo 'aria-current="page"'; ?>
               href="<?= $this->url('docente-alta-oferta') ?>"><i class="bi bi-plus-square-fill"> Alta oferta</i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link  <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_TRABAJOS_TUTORIZADOS_DOCENTE) echo 'active'; ?>"
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == 'home') echo 'aria-current="page"'; ?>
               href="<?= $this->url('docente-trabajos-tutorizados') ?>"><i class="bi bi-clipboard2-check-fill"></i>
                Trabajos
                tutorizados
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_SOLICITUDES_DEPOSITO_DOCENTE) echo 'active'; ?>"
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_SOLICITUDES_DEPOSITO_DOCENTE) echo 'aria-current="page"'; ?>
               href="<?= $this->url('docente-solicitudes-deposito') ?>"><i class="bi bi-mortarboard-fill"></i>
                Solicitudes de
                depósito
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link  <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_TRABAJOS_CALIFICADOS_DOCENTE) echo 'active'; ?>"
                <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == Constantes::RUTA_TRABAJOS_CALIFICADOS_DOCENTE) echo 'aria-current="page"'; ?>
               href="<?= $this->url('docente-trabajos-calificados') ?>"><i class="bi bi-award-fill"></i> Trabajos
                calificados
            </a>
        </li>
    </ul>

    <span class="navbar-text user_info">
        <?php if ($sesion->offsetExists(Constantes::SESION_NOMBRE_USUARIO)) { ?>
            <i class="bi bi-person-square"></i><i><?= $sesion->offsetGet(Constantes::SESION_NOMBRE_USUARIO); ?></i>
        <?php } ?>
        &nbsp&nbsp
    </span>
    <span class="navbar-text">
        <a class="nav-link" href="<?= $this->url('desconectar') ?>">
            Desconectar <i class="bi bi-box-arrow-in-right"></i>
        </a>
    </span>

</div>
