<!-- Modal -->
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" id="btn-modalNormativa" data-bs-toggle="modal"
        data-bs-target="#normativaModal" hidden>
    Launch modal
</button>

<div class="modal fade" id="normativaModal" tabindex="-1" aria-labelledby="normativaModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bck-primary-ligth">
                <h5 class="modal-title" id="normativaModalLabel">Normativa TFE</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <div class="normativa_modal">
                    <p>
                        Para realizar un Trabajo Fin de Estudios debe haber superado todas las asignaturas de su plan de
                        estudios.
                        Además el trabajo pasará a formar parte del archivo abierto de la biblioteca UOC que será
                        visible para todos
                        los usuarios registrados.
                    </p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-modal-cerrar" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-danger btn-submit-modal-normativa" data-bs-dismiss="modal">Acepto
                    la
                    normativa
                </button>
            </div>
        </div>
    </div>
</div>

