<!-- Button trigger modal -->
<!--<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#confirmarModal">
    Launch demo modal
</button>-->

<!-- Modal -->
<div class="modal fade" id="confirmarModal" tabindex="-1" aria-labelledby="confirmarModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bck-primary-ligth">
                <h5 class="modal-title" id="confirmarModalLabel">Confirmación de la acción</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>¿Está usted segur@ de que quiere realizar esta acción?</p>
                <div class="informacion_modal">
                    <p id="autorizar">Una vez autorizado el depósito del trabajo final, no podrá solicitar cambios.<br>
                        <label id="label_nota" for="nota">Nota final</label>
                        <input type="number" min="5" max="10" step="0.1" name="nota_final"></p>
                    <span class="text-danger hidden" id="error_modal">Debe indicar un valor numérico entre 0 y 10</span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-danger btn-submit-modal">Guardar cambios</button>
            </div>
        </div>
    </div>
</div>

