<!-- Button trigger modal -->
<!--<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#confirmarModal">
    Launch demo modal
</button>-->

<!-- Modal -->
<div class="modal fade" id="confirmarModal" tabindex="-1" aria-labelledby="confirmarModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bck-primary-ligth">
                <h5 class="modal-title" id="confirmarModalLabel">Confirmación de la acción</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>¿Está usted segur@ de que quiere realizar esta acción?</p>
                <div class="informacion_modal">
                    <p id="denegar" hidden>
                        Una vez denegado el deposito del trabajo no podrá realizar otra acción.
                    </p>
                    <p id="cambios" hidden>
                        Puede solicitar cambios en el trabajo tantas veces como desee. Indique alguna observación si lo
                        considera oportuno. Esta será visible para el estudiante.<br><br>
                        <textarea name="observaciones_modal" rows="2" disabled></textarea>
                    </p>
                    <p id="denegar_oferta_estudiante" hidden>
                        Indique observaciones.<br><br>
                        <textarea name="observaciones_denegacion_oferta_modal" rows="2" disabled></textarea>
                    </p>
                    <p id="autorizar" hidden>Una vez autorizado el depósito del trabajo final, no podrá solicitar
                        cambios.<br>
                        <label id="label_nota" for="nota">Nota final</label>
                        <input type="number" min="5" max="10" step="0.1" name="nota_modal" disabled>
                    </p>
                    <span class="text-danger" hidden
                          id="error_modal">Debe indicar un valor numérico entre 5 y 10
                    </span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-modal-cerrar" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-danger btn-submit-modal">Guardar cambios</button>
            </div>
        </div>
    </div>
</div>

