<!-- Button trigger modal -->
<!--<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#confirmarModal">
    Launch demo modal
</button>-->

<!-- Modal -->
<div class="modal fade" id="confirmarDepositoModal" tabindex="-1" aria-labelledby="confirmarDepositoModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bck-primary-ligth">
                <h5 class="modal-title" id="confirmarDepositoModalLabel">Confirmación de la acción</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>¿Está usted segur@ de que quiere realizar la solicitud de depósito de su trabajo? <br> Una vez
                    realizada, quedará pendiente por tramitar por parte de su tutor pudiendo solicitar este cambios
                    sobre el mismo.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-modal-cerrar" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-danger btn-submit-modal-deposito">Confirmar</button>
            </div>
        </div>
    </div>
</div>

