<!-- Button trigger modal -->
<!--<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#solicitarOferta">
    Launch demo modal
</button>-->


<!-- Vertically centered modal -->
<!-- Modal -->
<div class="modal fade" id="solicitarOferta" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Planes vigentes</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="estudios" class="form-label">Seleccione el plan para el que desea solicitar el
                        trabajo </label>
                    <select for="estudios" class="form-control" aria-label="Default select example" name="plan_trabajo"
                            id="plan_trabajo_modal">
                        <option selected>Seleccione</option>
                        <?php foreach ($this->planes as $plan) { ?>
                            <option value="<?= $plan['COD_PLAN'] ?>"><?= $plan['NOMBRE_PLAN'] ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary btn-submit-modal">Solicitar
                </button>
            </div>
        </div>
    </div>
</div>