<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<br><br><br><br>


<?= $this->partial('partials/errores') ?>
<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-1"><?= $texto ?></h1>

    <form action="" name="loginForm" method="post">
        <!-- Email input -->
        <div class="form-outline mb-4">
            <label class="form-label" for="mail">Email </label>
            <input type="email" name="email" id="mail" class="form-control"/>
        </div>

        <!-- Password input -->
        <div class="form-outline mb-4">
            <label class="form-label" for="pass">Password</label>
            <input type="password" name="password" id="pass" class="form-control"/>
        </div>

        <!-- 2 column grid layout for inline styling -->
        <!-- <div class="row">
             <div class="col d-flex justify-content-center">

                 <div class="form-check">
                     <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked/>
                     <label class="form-check-label" for="form2Example31"> Remember me </label>
                 </div>
             </div>

             <div class="col">

                 <a href="#!">¿Olvidó su contraseña?</a>
             </div>
         </div> -->

        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">Loguearse</button>


    </form>


</div>


