<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>

<br>
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Docente</li>
        <li class="breadcrumb-item active" aria-current="page">Alta oferta</li>
    </ol>
</nav>

<?= $this->partial('partials/errores') ?>


<div class="container-lg">
    <div class="bck-primary-ligth">
        <div class="d-flex justify-content-center">
            <p>
            <h1><b><?php if (!empty($oferta['COD_OFERTA'])) echo 'Editar'; else 'Alta'; ?> oferta</b></h1></p>
        </div>
    </div>
    <br>
    <form name="proponerForm" action="<?= $this->url('docente-alta-oferta') ?>" method="post">
        <br>
        <!--<h2>Proponer Trabajo</h2>-->
        <div class="alert alert-default border-dark" role="alert">
            <p>Para proponer un Trabajo Fin de Grado o Trabajo Fin de Máster debe indicar el área de estudios,
                asignatura y realizar una breve descripción del mismo.</p>
        </div>
        <div class="mb-3">
            <label for="area" class="form-label">Área de conocimiento</label>
            <select for="area" class="form-control" aria-label="Default select example" name="area"
                    required>
                <option selected>Seleccione</option>
                <?php foreach ($this->areas as $area) { ?>
                    <option value="<?= $area['COD_AREA'] ?>>"
                        <?php if (!empty($oferta)) { ?>
                            <?php if ($area['COD_AREA'] == $oferta['COD_OFERTA']) echo 'selected'; ?>
                        <?php } ?>
                    ><?= $area['NOMBRE_AREA'] ?></option>
                <?php } ?>
            </select>
        </div>


        <div class="mb-3">
            <label for="titulo" class="form-label">Título del trabajo</label>
            <input type="text" name="titulo" class="form-control" id="titulo"
                <?php if (!empty($oferta)) { ?>
                    value="<?= $oferta['TITULO'] ?>";
                <?php } ?>
                   required>
        </div>

        <div class="mb-3">
            <label for="subitulo" class="form-label">Subtítulo </label>
            <input type="text" name="subtitulo" class="form-control" id="subtitulo"
                <?php if (!empty($oferta)) { ?>
                    value="<?= $oferta['SUBTITULO'] ?>";
                <?php } ?>
                   required>
        </div>


        <div class="mb-3">
            <div class="mb-3">
                <label for="descripción" class="form-label">Descripción del Trabajo</label>
                <textarea name="descripcion" class="form-control" id="descripcion" rows="3" required>
                       <?php if (!empty($oferta)) { ?>
                           <?= $oferta['DESCRIPCION'] ?>
                       <?php } ?>
                </textarea>
            </div>

            <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                    data-bs-target="#docenteAltaModal">Enviar propuesta
            </button>

            <input type="hidden" name="flg_editar" value="<?php if (!empty($oferta['COD_OFERTA'])) echo 1; ?>">
    </form>

</div>
<br>


<?= $this->partial('partials/modal-docente-alta.phtml'); ?>

<form method="post" name="solicitudForm" action="">
    <input type="hidden" name="accion" value="">
    <input type="hidden" name="cod_oferta" value="">
    <input type="hidden" name="plan_trabajo" value="">
    <input type="hidden" name="flg" value="">
</form>
