<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>

<br>
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Docente</li>
        <li class="breadcrumb-item active" aria-current="page">Alta oferta</li>
    </ol>
</nav>


<div class="container-lg">
    <div class="bck-primary-ligth">
        <div class="d-flex justify-content-center">
            <p>
            <h1><b>Alta oferta</b></h1></p>
        </div>
    </div>
    <br>
    <form name="proponerOfertaForm" action="<?= $this->url('docente-alta-oferta') ?>" method="post">
        <br>

        <?php if (!empty($oferta['COD_OFERTA'])) { ?>
            <div class="alert alert-warning" role="alert">
                <p>Se dispone a editar una oferta de Trabajo Final.</p>
            </div>
        <?php } else { ?>
            <div class="alert alert-default border-dark" role="alert">
                <p>Para proponer un Trabajo Fin de Grado o Trabajo Fin de Máster debe indicar el área de estudios,
                    asignatura y realizar una breve descripción del mismo.</p>
            </div>
        <?php } ?>

        <!--feedback form-validation-->
        <div class='alert alert-danger alert-dismissable fade show error-form' role='alert' hidden>
            <b>Revise el formulario, existen campos obligatorios que no ha completado.</b>
        </div>
        <div class='alert alert-success alert-dismissable fade show success-form' role='alert' hidden>
            <b>Formulario completado correctamente.</b>
        </div>
        <!--- -->

        <div class="mb-3">
            <label for="area" class="form-label">Área de conocimiento</label>
            <select for="area" class="form-control" aria-label="Default select example" name="area"
                    required>
                <option value="" selected>Seleccione el área de conocimiento</option>
                <?php foreach ($this->areas as $area) { ?>
                    <option value="<?= $area['COD_AREA'] ?>"
                        <?php if (!empty($oferta)) { ?>
                            <?php if ($area['COD_AREA'] == $oferta['COD_OFERTA']) echo 'selected'; ?>
                        <?php } ?>
                    ><?= $area['NOMBRE_AREA'] ?></option>
                <?php } ?>
            </select>
        </div>


        <div class="mb-3">
            <label for="titulo" class="form-label">Título del trabajo</label>
            <input type="text" name="titulo" placeholder="Título" class="form-control" id="titulo"
                <?php if (!empty($oferta)) { ?>
                    value="<?= $oferta['TITULO'] ?>";
                <?php } ?>
                   required>
        </div>

        <div class="mb-3">
            <label for="subitulo" class="form-label">Subtítulo </label>
            <input type="text" name="subtitulo" placeholder="Subtítulo" class="form-control" id="subtitulo"
                <?php if (!empty($oferta)) { ?>
                    value="<?= $oferta['SUBTITULO'] ?>";
                <?php } ?>
                   required>
        </div>


        <div class="mb-3">
            <div class="mb-3">
                <label for="descripción" class="form-label">Descripción del Trabajo</label>
                <textarea name="descripcion" placeholder="Descripción" class="form-control" id="descripcion" rows="3"
                          required><?php if (!empty($oferta)) echo $oferta['DESCRIPCION']; ?></textarea>
            </div>

            <!-- boton function success form validation-->
            <button type="button" class="btn btn-primary boton_modal" data-bs-toggle="modal"
                    data-bs-target="#docenteAltaModal" hidden>Enviar propuesta modal
            </button>

            <!-- boton trigger form-validation -->
            <button type="submit" class="btn btn-primary">Guardar oferta</button>

            <input type="hidden" name="flg_editar" value="<?php if (!empty($oferta['COD_OFERTA'])) echo 1; ?>">
            <input type="hidden" name="cod_oferta"
                   value="<?php if (!empty($oferta['COD_OFERTA'])) echo $oferta['COD_OFERTA']; else null; ?>">
    </form>
</div>
<br>

<?= $this->partial('partials/modal-docente-alta.phtml'); ?>

