<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<br>
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">UOC</a></li>
        <li class="breadcrumb-item active" aria-current="page">Solicitudes depósito</li>
    </ol>
</nav>


<div class="container-lg">

    <div class="bck-primary-ligth">
        <div class="d-flex justify-content-center">
            <p>
            <h1><b>Solicitudes depósito Trabajo Final</b></h1></p>
        </div>
    </div>

    <br>
    <h1>Solicitudes depósito Trabajo Final</h1>
    <div class="alert alert-default border-dark">
        A continuación se muestran las solicitudes de depósitod realizadas por los estudiantes que tutoriza. Puede
        autorizar, denegar o solicitar cambios sobre los trabajos. En este último caso, el estudiante verá las
        observaciones que haga al respecto.
    </div>
    <div class="mb-3">

        <br>
        <?= $this->partial('partials/errores') ?>

        <table class="table table-striped table-bordered table-hover" id="table_extensible">
            <thead>
            <tr>
                <th scope="col">Curso</th>
                <th scope="col">Título trabajo</th>
                <th scope="col">Plan</th>
                <th scope="col">Área</th>
                <th scope="col">Estudiante</th>
                <th scope="col">Estado</th>
                <th scope="col">Nota</th>
                <th scope="col">Trabajo</th>
                <th scope="col">Acciones</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($solicitudes as $k => $trabajo) { ?>
                <tr>
                    <th scope="row" class="col-md-1"> <?= $trabajo['CURSO_ACADEMICO'] ?></th>
                    <th> <?= $trabajo['TITULO'] ?></th>
                    <th><?= '(' . $trabajo['COD_PLAN'] . ')' . $trabajo['NOMBRE_PLAN'] ?></th>
                    <th><?= $trabajo['NOMBRE_AREA'] ?></th>
                    <th> <?= '<a href="mailto:' . $trabajo['USUARIO_ESTUDIANTE'] . '@uoc.edu"><i class="fa-solid fa-envelope"></i></a> ' . $trabajo['NOMBRE'] . ' ' . $trabajo['APELLIDO1'] . ' ' . $trabajo['APELLIDO2'] ?></th>
                    <th>
                        <?php
                        if ($trabajo['ESTADO_DEPOSITO'] == 'Denegado')
                            echo '<span class="badge bg-danger text-white" data-bs-toggle="tooltip" data-bs-placement="top" title="Depósito denegado.">Denegado</span>';
                        else if ($trabajo['ESTADO_DEPOSITO'] == 'Autorizado')
                            echo '<span class="badge bg-success text-white" data-bs-toggle="tooltip" data-bs-placement="top" title="Trabajo autorizado.">Autorizado</span>';
                        else if ($trabajo['ESTADO_DEPOSITO'] == 'Pendiente')
                            echo '<span class="badge bg-primary text-white" data-bs-toggle="tooltip" data-bs-placement="top" title="Pendiente de tramitación">Pendiente</span>';
                        else if ($trabajo['ESTADO_DEPOSITO'] == 'Cambios solicitados')
                            echo '<span class="badge bg-warning bg-black" data-bs-toggle="tooltip" data-bs-placement="top" title="Cambios solicitados">Cambios solicitados</span>'; ?>

                    </th>
                    <th><?= $trabajo['NOTA_FINAL'] ?></th>
                    <th>
                        <button class="btn btn-sm btn-outline-dark">
                            <input type="hidden" name="fichero" value="<?= $trabajo['RUTA_FICHERO'] ?>">
                            <i class="bi bi-file-earmark-pdf">Trabajo</i>
                        </button>
                    </th>
                    <th>
                        <div class="d-grid gap-2">
                            <button type="button" class="btn btn-sm btn-success btn-tramitar-estudiante-deposito"
                                    data-bs-toggle='modal'
                                    data-bs-target="#confirmarModal"
                                    data-accion="autorizar"
                                    data-cod_oferta="<?= $trabajo['COD_OFERTA'] ?>"
                            >
                                Autorizar
                            </button>

                            <button type="button" class="btn btn-sm btn-danger btn-accion"
                                    data-bs-toggle="modal"
                                    data-bs-target="#confirmarModal"
                                    data-accion="denegar"
                                    data-cod_oferta="<?= $trabajo['COD_OFERTA']; ?>"
                            >Denegar
                            </button>

                            <button type="button" class="btn btn-sm btn-warning btn-accion "
                                    data-bs-toggle="modal"
                                    data-bs-target="#confirmarModal"
                                    data-accion="cambios"
                                    data-cod_oferta="<?= $trabajo['COD_OFERTA']; ?>"
                            >Solicitar cambios
                            </button>

                        </div>
                    </th>
                </tr>
            <?php } ?>
            </tbody>
        </table>

    </div>


    <button type="button" data-bs-toggle="modal" data-bs-target="#confirmarModal" hidden>
        Launch modal
    </button>
</div>


<?= $this->partial('partials/modal-confirmar.phtml'); ?>


<form method="post" name="solicitudForm" action="">
    <input type="hidden" name="accion" value="">
    <input type="hidden" name="cod_oferta" value="">
    <input type="hidden" name="nota_final" value="">
</form>
