<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Tfe\Util\Constantes;

?>


<br>
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">UOC</a></li>
        <li class="breadcrumb-item active" aria-current="page">Solicitudes depósito</li>
    </ol>
</nav>


<div class="container-lg">

    <div class="bck-primary-ligth">
        <div class="d-flex justify-content-center">
            <p>
            <h1><b>Solicitudes depósito Trabajo Final</b></h1></p>
        </div>
    </div>

    <br>
    <!--<h1>Solicitudes depósito Trabajo Final</h1>-->
    <div class="alert alert-default border-dark">
        <?= $this->partial('partials/leyenda'); ?>
        <p>
            A continuación se muestran las solicitudes de depósitod realizadas por los estudiantes que tutoriza. Puede
            autorizar, denegar o solicitar cambios sobre los trabajos. En este último caso, el estudiante verá las
            observaciones que haga al respecto.</p>
    </div>
    <div class="mb-3">

        <br>
        <?= $this->partial('partials/errores') ?>

        <table class="table table-striped table-bordered table-hover" id="table_extensible">
            <thead>
            <tr>
                <th scope="col">Curso</th>
                <th scope="col">Título trabajo</th>
                <th scope="col">Plan</th>
                <th scope="col">Área</th>
                <th scope="col">Estudiante</th>
                <th scope="col">Estado</th>
                <th scope="col">Nota</th>
                <th scope="col">Trabajo</th>
                <th scope="col">Acciones</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($solicitudes as $k => $trabajo) { ?>
                <tr>
                    <th scope="row" class="col-md-1"> <?= $trabajo['CURSO_ACADEMICO'] ?></th>
                    <th> <?= $trabajo['TITULO'] ?></th>
                    <th><?= '(' . $trabajo['COD_PLAN'] . ')' . $trabajo['NOMBRE_PLAN'] ?></th>
                    <th><?= $trabajo['NOMBRE_AREA'] ?></th>
                    <th> <?= '<a href="mailto:' . $trabajo['USUARIO_ESTUDIANTE'] . '@uoc.edu"><i class="fa-solid fa-envelope"></i></a> ' . $trabajo['NOMBRE'] . ' ' . $trabajo['APELLIDO1'] . ' ' . $trabajo['APELLIDO2'] ?></th>
                    <th>
                        <?php
                        if ($trabajo['ESTADO_DEPOSITO'] == Constantes::ESTADO_DEPOSITO_DENEGADO)
                            echo '<span class="badge bg-danger text-white" data-bs-toggle="tooltip" data-bs-placement="top" title="Depósito denegado.">Denegado</span>';
                        else if ($trabajo['ESTADO_DEPOSITO'] == Constantes::ESTADO_DEPOSITO_AUTORIZADO)
                            echo '<span class="badge bg-success text-white" data-bs-toggle="tooltip" data-bs-placement="top" title="Trabajo autorizado.">Autorizado</span>';
                        else if ($trabajo['ESTADO_DEPOSITO'] == Constantes::ESTADO_DEPOSITO_PENDIENTE)
                            echo '<span class="badge bg-primary text-white" data-bs-toggle="tooltip" data-bs-placement="top" title="Pendiente de tramitación">Pendiente</span>';
                        else if ($trabajo['ESTADO_DEPOSITO'] == Constantes::ESTADO_DEPOSITO_CAMBIOS_SOLICITADOS)
                            echo '<span class="badge bg-warning text-black" data-bs-toggle="tooltip" data-bs-placement="top" title="Observaciones: ' . $trabajo['OBSERVACIONES'] . '">Cambios solicitados</span>'; ?>

                    </th>
                    <th><?= $trabajo['NOTA_FINAL'] ?></th>
                    <th>
                        <form name="downloadForm" action="<?= $this->url('descargar-fichero') ?>" method="post">
                            <button type="submit" class="btn btn-sm btn-outline-dark">
                                <input type="hidden" name="cod_solicitud" value="<?= $trabajo['COD_SOLICITUD'] ?>">
                                <i class="bi bi-file-earmark-pdf">Trabajo</i>
                            </button>
                        </form>
                    </th>
                    <th class="text-center">
                        <div class="d-grid gap-2">
                            <?php if (empty($trabajo['NOTA_FINAL']) && in_array($trabajo['ESTADO_DEPOSITO'], [Constantes::ESTADO_DEPOSITO_PENDIENTE, Constantes::ESTADO_DEPOSITO_DENEGADO])) { ?>
                                <button type="button" class="btn btn-sm btn-success btn-tramitar-estudiante-deposito"
                                        data-bs-toggle='modal'
                                        data-bs-target="#confirmarModal"
                                        data-accion="autorizar"
                                        data-cod_solicitud="<?= $trabajo['COD_SOLICITUD'] ?>"
                                        data-cod_oferta="<?= $trabajo['COD_OFERTA'] ?>"
                                >
                                    Autorizar
                                </button>


                                <button type="button" class="btn btn-sm btn-danger btn-tramitar-estudiante-deposito"
                                        data-bs-toggle="modal"
                                        data-bs-target="#confirmarModal"
                                        data-accion="denegar"
                                        data-cod_oferta="<?= $trabajo['COD_OFERTA']; ?>"
                                        data-cod_solicitud="<?= $trabajo['COD_SOLICITUD'] ?>"
                                >Denegar
                                </button>

                                <button type="button" class="btn btn-sm btn-warning btn-tramitar-estudiante-deposito"
                                        data-bs-toggle="modal"
                                        data-bs-target="#confirmarModal"
                                        data-accion="cambios"
                                        data-cod_oferta="<?= $trabajo['COD_OFERTA']; ?>"
                                        data-cod_solicitud="<?= $trabajo['COD_SOLICITUD'] ?>"
                                >Solicitar cambios
                                </button>
                            <?php } ?>
                        </div>
                    </th>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>

</div>


<?= $this->partial('partials/modal-confirmar.phtml'); ?>


<form method="post" name="solicitudForm" action="<?= $this->url('docente-guardar-tramitar-estudiante-deposito') ?>">
    <input type="hidden" name="accion" value="">
    <input type="hidden" name="cod_oferta" value="">
    <input type="hidden" name="cod_solicitud" value="">
    <input type="hidden" name="nota_final" value="">
    <input type="hidden" name="observaciones" value="">
</form>
