<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<br>
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">UOC</a></li>
        <li class="breadcrumb-item active" aria-current="page">Trabajos calificados</li>
    </ol>
</nav>


<div class="container-lg">

    <div class="bck-primary-ligth">
        <div class="d-flex justify-content-center">
            <p>
            <h1><b>Trabajos calificados</b></h1></p>
        </div>
    </div>

    <br>
    <!--  <h1>Trabajos calificados</h1> -->
    <div class="alert alert-default border">
        A continuación se muestra el histórico de trabajos calificados.
    </div>
    <div class="mb-3">

        <br>

        <?= $this->partial('partials/errores') ?>

        <hr>
        <table class="table table-striped table-bordered table-hover" id="table_extensible">
            <thead>
            <tr>
                <th scope="col">Curso</th>
                <th scope="col">Plan</th>
                <th scope="col">Área</th>
                <th scope="col">Estudiante</th>
                <th scope="col">Nota media</th>
                <th scope="col">Nota final</th>
            </tr>
            </thead>
            <tbody>
            <?php if (!empty($trabajos)) { ?>
                <?php foreach ($trabajos as $trabajo) { ?>
                    <tr>
                        <th scope="row" class="col-md-3"> <?= $trabajo['CURSO_ACADEMICO'] ?></th>
                        <th> <?= '(' . $trabajo['COD_PLAN'] . ') ' . $trabajo['NOMBRE_PLAN'] ?></th>
                        <th> <?= $trabajo['NOMBRE_AREA'] ?></th>
                        <th> <?= $trabajo['NOMBRE'] . ' ' . $trabajo['APELLIDO1'] . ' ' . $trabajo['APELLIDO2'] ?></th>
                        <th><?= random_int(0, 10) ?>
                        </th>
                        <th><?= $trabajo['NOTA_FINAL'] ?>
                        </th>
                    </tr>
                <?php }
            } ?>
            </tbody>
        </table>

    </div>


    <button type="button" data-bs-toggle="modal" data-bs-target="#confirmarModal" hidden>
        Launch modal
    </button>
</div>

<?= $this->partial('partials/modal-solicitar-oferta.phtml', ['planes' => $this->planes_estudiante]); ?>

<?= $this->partial('partials/modal-confirmar.phtml'); ?>


<form method="post" name="solicitudForm" action="">
    <input type="hidden" name="accion" value="">
    <input type="hidden" name="cod_oferta" value="">
    <input type="hidden" name="plan_trabajo" value="">
    <input type="hidden" name="flg" value="">
</form>

