<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Laminas\Session\Container;
use Tfe\Util\Constantes;

$sesion = new Container (Constantes::NOMBRE_SESION);
?>


<?= $this->doctype() ?>
<html lang="es" class="h-100">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('UOC Portal TFE')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        // ->prependStylesheet($this->basePath('css/responsive.bootstrap5.min.css'))
        ->prependStylesheet($this->basePath('css/responsive.datatables.css'))
        ->prependStylesheet($this->basePath('css/datatables.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300&family=Roboto:wght@300&display=swap"
          rel="stylesheet">
    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/datatables.js'))
        ->prependFile($this->basePath('js/table-datatables-responsive.js'))
        ->prependFile($this->basePath('js/functions.js'))
        //->prependFile("https://kit.fontawesome.com/a9538ddc2f.js")
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</head>
<body class="d-flex flex-column h-100">


<!--<nav class="navbar navbar-expand-lg fixed-top navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img class="img-logo" src="<? //= $this->basePath('img/logo-uoc-default.png') ?>" alt="UOC-logo"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-evenly" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="<? //= $this->url('home') ?>">Inicio</a>
                <a class="nav-link" href="<? //= $this->url('mi-perfil') ?>">Mi expediente</a>
                <a class="nav-link" href="<? //= $this->url('trabajos-ofertados') ?>">Oferta de
                    temas</a>
                <a class="nav-link" href="<? //= $this->url('propuesta-oferta') ?>">Proponer tema</a>
                <a class="nav-link" href="<? //= $this->url('solicitud-deposito') ?>">Solicitud
                    depósito</a>
            </div>
        </div>
    </div>
</nav>-->


<nav class="navbar navbar-dark navbar-expand-lg fixed-top flex-column flex-lg-row" role="navigation">
    <a class="nav-link flex-sm-fill text-center" href="<?= $this->url('home') ?>">
        <img class="img-logo" src="<?= $this->basePath('img/logo-uoc-default.png') ?>" alt="UOC-logo">
    </a>
    <a class="flex-sm-fill nav-link text-white <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == 'home') echo 'menu-active'; ?>"
       href="<?= $this->url('home') ?>">Inicio</a>
    <a class="flex-sm-fill nav-link text-white <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == 'mi-perfil') echo 'menu-active'; ?>"
       href="<?= $this->url('mi-perfil') ?>">Mi
        perfil</a>
    <a class="flex-sm-fill nav-link text-white <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == 'trabajos-ofertados') echo 'menu-active'; ?>"
       href="<?= $this->url('trabajos-ofertados') ?>">Trabajos
        ofertados</a>
    <a class="flex-sm-fill nav-link text-white <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == 'propuesta-oferta') echo 'menu-active'; ?>"
       href="<?= $this->url('propuesta-oferta') ?>">Proponer
        Oferta</a>
    <a class="flex-sm-fill nav-link text-white <?php if ($sesion->offsetExists(Constantes::CURRENT_URL) && $sesion->offsetGet(Constantes::CURRENT_URL) == 'solicitud-deposito') echo 'menu-active'; ?>"
       href="<?= $this->url('solicitud-deposito') ?>">Solicitud
        depósito</a>
</nav>

<main class="flex-shrink-0">
    <div class="container">
        <?= $this->content ?>
        <hr>
    </div>
</main>

<footer class="footer mt-auto py-3 bck-primary-ligth">
    <div class="container">
        <p>
            &copy; <?= date('Y') ?>
            <a target="_blank" href="https://github.com/estrellapsanz/laminas-tfm">UOC TFM </a> ESTRELLA
            PARRILLA
            SANZ.
        </p>
    </div>
</footer>
<?php echo $this->headScript(); ?>
<script>
    jQuery(document).ready(function () {
        TableDatatablesResponsive.init();
    });
</script>
</body>
</html>
