<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('UOC Portal TFM')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        // ->prependStylesheet($this->basePath('css/responsive.bootstrap5.min.css'))
        ->prependStylesheet($this->basePath('css/responsive.datatables.css'))
        ->prependStylesheet($this->basePath('css/datatables.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300&family=Roboto:wght@300&display=swap"
          rel="stylesheet">
    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/datatables.js'))
        ->prependFile($this->basePath('js/table-datatables-responsive.js'))
        ->prependFile($this->basePath('js/functions.js'))
        ->prependFile("https://kit.fontawesome.com/a9538ddc2f.js")
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</head>
<body>
<nav class="navbar navbar-dark flex-column flex-sm-row " role="navigation">
    <a class="flex-sm-fill text-sm-center" href="<?= $this->url('home') ?>">
        <img class="img-logo" src="<?= $this->basePath('img/logo-uoc-default.png') ?>" alt="UOC-logo">
    </a>
    <a class="flex-sm-fill text-sm-left nav-link text-white" href="<?= $this->url('mi-perfil') ?>">Mi perfil</a>
    <a class="flex-sm-fill text-sm-left nav-link text-white" href="<?= $this->url('trabajos-ofertados') ?>">Trabajos
        ofertados</a>
    <a class="flex-sm-fill text-sm-left nav-link text-white" href="<?= $this->url('propuesta-oferta') ?>">Proponer
        Oferta</a>
    <a class="flex-sm-fill text-sm-left nav-link text-white" href="<?= $this->url('solicitud-deposito') ?>">Solicitud
        depósito</a>

</nav>
<div class="container">
    <?= $this->content ?>
    <hr>
    <footer>
        <p>
            &copy; <?= date('Y') ?>
            <a target="_blank" href="https://github.com/estrellapsanz/laminas-tfm">UOC TFM </a> ESTRELLA PARRILLA SANZ,
            2022.
        </p>
    </footer>
</div>
<?php echo $this->headScript(); ?>
<script>
    jQuery(document).ready(function () {
        TableDatatablesResponsive.init();
    });
</script>
</body>
</html>
