<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('UOC Portal TFM')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>
<body>
<nav class="navbar navbar-dark flex-column flex-sm-row " role="navigation">
    <a class="flex-sm-fill text-sm-center" href="<?= $this->url('home') ?>">
        <img class="img-logo" src="<?= $this->basePath('img/logo-uoc-default.png') ?>" alt="UOC-logo">
    </a>
    <a class="flex-sm-fill text-sm-left nav-link text-white" href="#">Mi perfil</a>
    <a class="flex-sm-fill text-sm-left nav-link text-white" href="#">Estudios de Grado</a>
    <a class="flex-sm-fill text-sm-left nav-link text-white">Biblioteca</a>
</nav>
<div class="container">
    <?= $this->content ?>
    <hr>
    <footer>
        <p>
            &copy; <?= date('Y') ?>
            <a target="_blank" href="https://github.com/estrellapsanz/laminas-tfm">UOC TFM </a> ESTRELLA PARRILLA SANZ,
            2022.
        </p>
    </footer>
</div>
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/functions.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body>
</html>
