<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('home') ?>">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Trabajos ofertados</li>
    </ol>
</nav>


<div class="container bck-primary">
    <div class="container text-center">
        <div class="row align-items-start">
            <div class="col">
                <p><b>Trabajos Ofertados</b></p>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="d-flex">
        <div class="flex-grow-1 ms-3">
            <h2>Trabajos ofertados curso <?= $curso ?></h2>
            <div class="mb-3">
                <?php foreach ($this->ofertas as $area => $ofertas_area) { ?>
                    <br>
                    <label for="estudios" class="form-label"><b> <?= $area ?></b></label>
                    <hr>
                    <table class="table table-striped" id="table_extensible">
                        <thead>
                        <tr>
                            <th scope="col">Título</th>
                            <th scope="col">Descripción</th>
                            <th scope="col">Tutor</th>
                            <th scope="col">Área</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($ofertas_area as $oferta) { ?>
                            <tr>
                                <th scope="row"> <?= $oferta['TITULO'] ?></th>
                                <th> <?= $oferta['DESCRIPCION'] ?></th>
                                <th> <?= $oferta['NOMBRE'] ?></th>
                                <th> <?= $oferta['NOMBRE_AREA'] ?></th>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>

                <?php } ?>
            </div>


            <!--<div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Propuesta de TFM</label>
                <textarea name="propuesta" class="form-control" id="exampleFormControlTextarea1"
                          rows="3"></textarea>
            </div>-->
            <!-- <div class="mb-3 form-check">
                 <input type="checkbox" class="form-check-input check-normativa" id="normativa">
                 <label class="form-check-label" for="normativa">He leído la normativa de TFM.</label>
             </div>-->

            <!--<button type="submit" class="btn btn-primary">Enviar</button>-->

        </div>
    </div>
</div>

