<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('home') ?>">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Trabajos ofertados</li>
    </ol>
</nav>


<div class="container bck-primary">
    <div class="container text-center">
        <div class="row align-items-start">
            <div class="col">
                <p><b>Trabajos Ofertados</b></p>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="d-flex">
        <div class="flex-shrink-0">
            <img src="<?= $this->basePath() ?>/img/user.png" class="img-thumbnail img-fluid"
                 alt="imagen de perfil de un usuario">
        </div>
        <div class="flex-grow-1 ms-3">
            <h2>Datos del estudiante</h2>
            <div class="mb-3">
                <label for="name" class="form-label">Nombre</label>
                <input type="text" class="form-control" id="name"
                       value="<?= $this->estudiante[0]['NOMBRE'] . ' ' . $this->estudiante[0]['APELLIDO1'] . ' ' . $this->estudiante[0]['APELLIDO2'] ?>"
                       readonly disabled>
            </div>

            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Email address</label>
                <input type="email" class="form-control" id="exampleFormControlInput1"
                       placeholder="name@example.com"
                       value="<?= $this->estudiante[0]['USUARIO'] . '@uoc.edu'; ?>" readonly disabled>
            </div>

            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Teléfono</label>
                <input type="email" class="form-control" id="exampleFormControlInput1"
                       placeholder="Teléfono1"
                       value="<?= $this->estudiante[0]['TELEFONO1'] ?>" readonly disabled>
            </div>

            <h2>Datos académicos</h2>
            <div class="mb-3">
                <?php foreach ($this->estudiante as $estudios) { ?>
                    <br>
                    <label for="estudios" class="form-label"><b> <?= $estudios['NOMBRE_PLAN'] ?></b></label>
                    <hr>
                    <?php if (!empty($estudios['ASIGNATURAS'])) { ?>
                        <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Curso</th>
                            <th scope="col">Asignatura</th>
                            <th scope="col">Nota</th>
                            <th scope="col">Calificación</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($estudios['ASIGNATURAS'] as $asignatura) { ?>
                            <tr>
                                <th scope="row"> <?= $asignatura['CURSO_ACADEMICO'] ?></th>
                                <th> <?= $asignatura['NOMBRE_ASIGNATURA'] ?></th>
                                <th> <?= $asignatura['NOTA_NUMERICA'] ?></th>
                                <th> <?= $asignatura['NOTA_ALFANUMERICA'] ?></th>
                            </tr>
                        <?php } ?>
                    <?php } ?>
                    </tbody>
                    </table>
                <?php } ?>
            </div>


            <!--<div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Propuesta de TFM</label>
                <textarea name="propuesta" class="form-control" id="exampleFormControlTextarea1"
                          rows="3"></textarea>
            </div>-->
            <!-- <div class="mb-3 form-check">
                 <input type="checkbox" class="form-check-input check-normativa" id="normativa">
                 <label class="form-check-label" for="normativa">He leído la normativa de TFM.</label>
             </div>-->

            <!--<button type="submit" class="btn btn-primary">Enviar</button>-->

        </div>
    </div>
</div>

